my_string = input('Здавствуйте, напишите всё что обо мне думаете, и я отвечу Вам сколько вы ввели символов:' )
length = (len(my_string))
you_string = ("Вы ввели "+str(length))
itog = you_string + ' символов'
print(itog)
my_string = input(('Здавствуйте, напишите всё что обо мне думаете, и я отвечу Вам сколько вы ввели символов:' .upper()) )
length = (len(my_string))
you_string = (("Вы ввели "+str(length)) .upper())
itog = you_string + ' символов' .upper()
print(itog)
print('Ваши данные в верхнем регистре' .upper(), my_string .upper())
my_string = input(('Здавствуйте, напишите всё что обо мне думаете, и я отвечу Вам сколько вы ввели символов:' .lower()) )
length = (len(my_string))
you_string = (("Вы ввели "+str(length)) .lower())
itog = you_string + ' символов' .lower()
print(itog)
print('Ваши данные в нижнем регистре' .lower(), my_string .lower())
my_string = input(('Здавствуйте, напишите всё что обо мне думаете, и я отвечу Вам сколько вы ввели символов:' .replace(' ', '')) )
length = (len(my_string))
you_string = (("Вы ввели "+str(length)) .replace(' ', ''))
itog = you_string + ' символов' .replace(' ', '')
print(itog)
print('Вы не сможете написать без пробела, Ваш результат:' .replace(' ', ''), my_string .replace(' ', ''))
print('Вы начали с: ', my_string[0])
print("Вы закончили: ", my_string[-1])